### ISSUE TITLE
Guess what was thrown today!

### ISSUE THREAD

**Issue by jwozcode123** [Blockception/Minecraft-Error-Codes#12]
Vs code kinda threw debugger/internal/exception.md

**Comment by DaanV2** [comment]
Do you have the logs for me?

https://faq.blockception.dev/vscode-extension-mcbe/console

**Comment by DaanV2** [comment]
Also first time reported :D

**Comment by jwozcode123** [comment]
yes i do have them

**Comment by jwozcode123** [comment]
[Info  - 9:43:13 AM] [code-actions] checking code actions {
  "textDocument": {
    "uri": "file:///c%3A/Users/jwozc/AppData/Local/Packages/Microsoft.MinecraftUWP_8wekyb3d8bbwe/LocalState/games/com.mojang/development_behavior_packs/Chair%20item/items/chairitem.item.json"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 0,
      "character": 1
    }
  },
  "context": {
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 1
          }
        },
        "message": "Cannot convert undefined or null to object\n\tTypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at minecraft:icon (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:804608)\n    at c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:151988\n    at Array.forEach (<anonymous>)\n    at n (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:151959)\n    at t.components_check (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:151773)\n    at t.behaviorpack_diagnose_item_components (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:802212)\n    at t.Diagnose (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:805397)\n    at e.Process (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:470763)\n    at t.Diagnoser.process (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:533786)",
        "code": "debugger.internal.exception",
        "codeDescription": {
          "href": "https://github.com/Blockception/Minecraft-Error-Codes/blob/main/debugger/internal/exception.md"
        },
        "severity": 1,
        "source": "mc"
      }
    ],
    "only": [
      "quickfix"
    ],
    "triggerKind": 1
  }
}
[Info  - 9:43:13 AM] [code-actions] checking code actions {
  "textDocument": {
    "uri": "file:///c%3A/Users/jwozc/AppData/Local/Packages/Microsoft.MinecraftUWP_8wekyb3d8bbwe/LocalState/games/com.mojang/development_behavior_packs/Chair%20item/items/chairitem.item.json"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 0,
      "character": 1
    }
  },
  "context": {
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 1
          }
        },
        "message": "Cannot convert undefined or null to object\n\tTypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at minecraft:icon (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:804608)\n    at c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:151988\n    at Array.forEach (<anonymous>)\n    at n (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:151959)\n    at t.components_check (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:151773)\n    at t.behaviorpack_diagnose_item_components (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:802212)\n    at t.Diagnose (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:805397)\n    at e.Process (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:470763)\n    at t.Diagnoser.process (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:533786)",
        "code": "debugger.internal.exception",
        "codeDescription": {
          "href": "https://github.com/Blockception/Minecraft-Error-Codes/blob/main/debugger/internal/exception.md"
        },
        "severity": 1,
        "source": "mc"
      }
    ],
    "only": [
      "quickfix"
    ],
    "triggerKind": 1
  }
}
[Info  - 9:43:18 AM] [code-actions] checking code actions {
  "textDocument": {
    "uri": "file:///c%3A/Users/jwozc/AppData/Local/Packages/Microsoft.MinecraftUWP_8wekyb3d8bbwe/LocalState/games/com.mojang/development_behavior_packs/Chair%20item/items/chairitem.item.json"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 0,
      "character": 1
    }
  },
  "context": {
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 1
          }
        },
        "message": "Cannot convert undefined or null to object\n\tTypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at minecraft:icon (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:804608)\n    at c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:151988\n    at Array.forEach (<anonymous>)\n    at n (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:151959)\n    at t.components_check (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:151773)\n    at t.behaviorpack_diagnose_item_components (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:802212)\n    at t.Diagnose (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:805397)\n    at e.Process (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:470763)\n    at t.Diagnoser.process (c:\\Users\\jwozc\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-8.0.18\\server\\out\\server.js:2:533786)",
        "code": "debugger.internal.exception",
        "codeDescription": {
          "href": "https://github.com/Blockception/Minecraft-Error-Codes/blob/main/debugger/internal/exception.md"
        },
        "severity": 1,
        "source": "mc"
      }
    ],
    "only": [
      "quickfix"
    ],
    "triggerKind": 1
  }
}

**Comment by jwozcode123** [comment]
Is this good?

**Comment by DaanV2** [comment]
Yes thank you!

**Comment by jwozcode123** [comment]
[Love the description💀😭. ](https://github.com/Blockception/Minecraft-Error-Codes/blob/5931f4a5c38d16c6979f31a380fb8b59b4277ea1/debugger/internal/exception.md)
